spring:
  application:
    name: HongBookStore
  config:
    import: optional:file:.env[.properties], optional:file:src/.env[.properties]

  ### OAuth ###
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID} # 발급 받은 Client ID
            client-secret: ${GOOGLE_CLIENT_SECRET} # 발급 받은 Client Secret
            scope: # 기본값 openid, profile, email => profile, email로 설정 변경
              - profile
              - email

          naver:
            client-id: ${NAVER_CLIENT_ID} # 발급 받은 Client ID
            client-secret: ${NAVER_CLIENT_SECRET} # 발급 받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            #            scope:
            #              - name
            #              - email
            #              - profile_image
            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID} # 발급 받은 Client ID
            client-secret: ${KAKAO_CLIENT_SECRET} # 발급 받은 Client Secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

  ### JavaMailSender ###
  mail: # 이메일을 전송할 SMTP 서버 설정
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버에 로그인할 때 인증을 사용할지를 결정
          starttls:
            enable: true # TLS를 사용할지를 결정
      debug: true # 디버그 모드 활성화 (선택 사항)

  ### MySQL DB ###
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://104.198.2.213:3306/hongBookstore?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  ### Redis DB ###
  data:
    redis:
      host: 104.198.2.213
      port: 6379

  ### JPA ###
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true # SQL 로그를 예쁘게 포맷팅
      show-sql: true # 실행되는 SQL 쿼리를 로그로 보여줌

  ### GCP Cloud Storage ###
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}  # .env 파일의 GCP_PROJECT_ID 값을 사용합니다.
      storage:
        bucket-name: ${GCP_BUCKET_NAME} # .env 파일의 GCP_BUCKET_NAME 값을 사용합니다.
      credentials:
        location: classpath:gcp-service-account-key.json # 키 파일은 그대로 resources 폴더에서 관리합니다.
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB # 업로드 파일 최대 크기 설정
        max-request-size: 10MB

### JWT ###
jwt:
  secret: ${JWT_SECRET_KEY} # JWT 토큰을 서명할 때 사용할 시크릿 키, base64 이용해 랜덤 생성함
  token-validity-in-seconds: 3600 # 토큰 유효 기간
  refresh-token-validity-in-seconds: 86400 # 리프레시 토큰 유효 기간

### Log ###
logging:
  level:
    root: info
    org:
        springframework:
            security: debug
    hibernate:
    sql: debug
    type:
        descriptor:
        sql: trace

### 프론트엔드 설정 ###
frontend:
  base-url: http://localhost:5173 # 로컬 개발 환경용 프론트엔드 주소

### Naver Map API ###
naver:
  map:
    client-id: ${VITE_NAVER_MAP_CLIENT_ID:n1y8pc9hl8}
    client-secret: ${VITE_NAVER_MAP_CLIENT_SECRET:}



### Swagger ###
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP 메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**