spring.application.name: HongBookStore

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hongbookstore-db.cl0asg8wa0o0.ap-northeast-2.rds.amazonaws.com:3306/hongBookstore?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: hongikbookproj
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

# 로그 설정
logging:
  level:
    root: info
    org:
        springframework:
            security: debug
    hibernate:
    sql: debug
    type:
        descriptor:
        sql: trace

jwt:
  secret: super-secret-key-change-me-0123456789
  expire-min: 60        # 액세스 토큰 유효기간(분) – 60분