name = "hongbook-api-proxy"
main = "worker.js"
compatibility_date = "2024-09-01"

# workers.dev 기본 도메인으로 배포(커스텀 도메인 없음)
# 환경변수는 GitHub Actions에서 주입하거나 [vars]로 기본값을 둘 수 있습니다.
[vars]
BACKEND_ORIGIN = "http://127.0.0.1:8080"  # 예시: GCE 공인IP로 교체
FRONT_ORIGIN = "*"                         # 예시: https://<pages>.pages.dev

