# Declarative Cloud Run service template for hongbookstore backend.
# Replace REGION/PROJECT_ID/REPOSITORY/IMAGE_TAG or override via `gcloud run deploy --image`.
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hongbookstore
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/hongbookstore:IMAGE_TAG
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            # Add other env vars here or via deploy.sh flags / Secret Manager.
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            limits:
              cpu: 1
              memory: 512Mi
