apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hongbookstore
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/hongbookstore:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            # 필요한 환경변수는 배포 시 CLI로 세팅하거나 Secret Manager를 사용하세요.
            # 아래는 예시이며 값은 비워두었습니다.
            #- name: MYSQL_HOST
            #  value: ""
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            limits:
              cpu: 1
              memory: 512Mi

